// OpenJam build:
// 1. Bundle the rrweb recorder into a classic content script (MV3 forbids
//    remote code, so rrweb ships inside the extension).
// 2. Bundle @rrweb/replay's Replayer into a classic script exposing
//    window.RRWebReplayer — rrweb-player@2.x ships broken dist artifacts (the
//    compiled component never constructs its Replayer; verified across
//    2.0.0/2.0.1 UMD+ESM builds), so OpenJam drives the replay engine directly
//    with its own controller UI (renderer.js mountReplay).
// 3. Emit the engine + its CSS as string constants for inlining into the
//    self-contained HTML export, and as extension files for the viewer page.
import { build } from "esbuild";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

await build({
  entryPoints: ["src/rrweb-recorder.js"],
  bundle: true,
  format: "iife",
  minify: true,
  outfile: "dist/rrweb-recorder.js",
  logLevel: "info",
});

await build({
  stdin: {
    contents: 'import { Replayer } from "@rrweb/replay";\nwindow.RRWebReplayer = Replayer;\n',
    resolveDir: process.cwd(),
    sourcefile: "replay-engine-entry.js",
  },
  bundle: true,
  format: "iife",
  minify: true,
  outfile: "dist/rrweb-replay.js",
  logLevel: "info",
});

const engine = readFileSync("dist/rrweb-replay.js", "utf8");
const engineCss = readFileSync("node_modules/@rrweb/replay/dist/style.min.css", "utf8");

// Both get inlined into an HTML <script>/<style>. The export neutralises
// </script>, but <!-- or <script would shift the HTML parser into a state that
// swallows the closing tag (https://html.spec.whatwg.org/multipage/scripting.html#restrictions-for-contents-of-script-elements).
if (/<\/script|<script|<!--/i.test(engine)) {
  throw new Error("replay engine bundle contains HTML-breaking sequences (<script, </script or <!--); review export inlining before shipping");
}

writeFileSync("dist/rrweb-replay.css", engineCss);
mkdirSync("src/generated", { recursive: true });
writeFileSync(
  "src/generated/player-assets.js",
  "// Generated by build.mjs — do not edit. Engine: @rrweb/replay@2.0.1.\n" +
    "export const ENGINE_IIFE = " + JSON.stringify(engine) + ";\n" +
    "export const ENGINE_CSS = " + JSON.stringify(engineCss) + ";\n",
);
console.log("wrote src/generated/player-assets.js, dist/rrweb-replay.{js,css}");
