// OpenJam build: (1) bundle the rrweb recorder into a classic content script
// (MV3 forbids remote code, so rrweb ships inside the extension), and
// (2) emit the rrweb-player UMD + CSS as string constants for inlining into
// the self-contained HTML export.
import { build } from "esbuild";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

await build({
  entryPoints: ["src/rrweb-recorder.js"],
  bundle: true,
  format: "iife",
  minify: true,
  outfile: "dist/rrweb-recorder.js",
  logLevel: "info",
});

const umd = readFileSync("node_modules/rrweb-player/dist/rrweb-player.umd.min.cjs", "utf8");
const css = readFileSync("node_modules/rrweb-player/dist/style.min.css", "utf8");
// The UMD gets inlined into an HTML <script>. The export neutralises </script>,
// but <!-- or <script would shift the HTML parser into a state that swallows
// the closing tag (https://html.spec.whatwg.org/multipage/scripting.html#restrictions-for-contents-of-script-elements).
// Today's build contains none of these — fail loudly if a future version does.
if (/<\/script|<script|<!--/i.test(umd)) {
  throw new Error("rrweb-player UMD contains HTML-breaking sequences (<script, </script or <!--); review export inlining before shipping");
}
mkdirSync("src/generated", { recursive: true });
writeFileSync(
  "src/generated/player-assets.js",
  "// Generated by build.mjs — do not edit. Source: rrweb-player@2.0.1 dist.\n" +
    "export const PLAYER_UMD = " + JSON.stringify(umd) + ";\n" +
    "export const PLAYER_CSS = " + JSON.stringify(css) + ";\n",
);
console.log("wrote src/generated/player-assets.js");
